# CONSTANT
CURRENT_DIR = $(shell pwd)
PROJECT_ROOT_DIR = $(CURRENT_DIR)

# TO CREATE
BUILD_DIRECTORY = $(PROJECT_ROOT_DIR)/build
PROJECT_MODULES_DIRECTORY = $(BUILD_DIRECTORY)/modules
PROJECT_BIN_DIRECTORY = $(BUILD_DIRECTORY)/bin
PROJECT_LIBS_DIRECTORY = $(BUILD_DIRECTORY)/lib
PROJECT_STATIC_LIB_DIRECTORY = $(PROJECT_LIBS_DIRECTORY)/static
PROJECT_DYNAMIC_LIB_DIRECTORY = $(PROJECT_LIBS_DIRECTORY)/dynamic

prepare:
	mkdir -p $(BUILD_DIRECTORY) \
			 $(PROJECT_MODULES_DIRECTORY) \
			 $(PROJECT_BIN_DIRECTORY) \
			 $(PROJECT_LIBS_DIRECTORY) \
			 $(PROJECT_STATIC_LIB_DIRECTORY) \
			 $(PROJECT_DYNAMIC_LIB_DIRECTORY)


check_vars:
	echo CURRENT_DIR: $(CURRENT_DIR)
	echo BUILD_DIRECTORY: $(BUILD_DIRECTORY)
	echo PROJECT_MODULES_DIRECTORY: $(PROJECT_MODULES_DIRECTORY)
	echo PROJECT_BIN_DIRECTORY: $(PROJECT_BIN_DIRECTORY)
	echo PROJECT_LIBS_DIRECTORY: $(PROJECT_LIBS_DIRECTORY)
	echo PROJECT_STATIC_LIB_DIRECTORY: $(PROJECT_STATIC_LIB_DIRECTORY)
	echo PROJECT_DYNAMIC_LIB_DIRECTORY: $(PROJECT_DYNAMIC_LIB_DIRECTORY)

clean:
	-rm -rf $(BUILD_DIRECTORY)


.DEFAULT_GOAL = check_vars